export default function Coffee() {
    return (

        <div style={{
            maxWidth: '350px'
            }}>
            <h3 style={{textAlign: 'center'}}>INFO/CONTACT</h3> 
            <p style={{textAlign: 'center'}}>INFO/CONTACT  INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT 
            INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT INFO/CONTACT 
            INFO/CONTACT INFO/CONTACT</p>
        </div>
    )
}